### ISSUE TITLE
UI Discussion and Implementation

### ISSUE THREAD

**Issue by Priyansh-15** [Priyansh-15/Job_Helper#14]
Design and Development of the UI for this project
The UI will include 4 Pages (As of now ....)
Page 1 : The data collector/ google form type
Page 2 : Category selection for the job fields
Page 3: The loading one
Page 4 : The result description

**Comment by koustubh1317** [comment]
UI Update:-
Navbar:- Some minor changes
Page 1:- 

- Title style change
- Index.html line 5,27 update
- Skills slider effect(1-10)
- Website and other links:- pre-filled links
- Resume in same json file 
- Button css change

Page 2:-
Ui To be discussed.....

Page 3:-
Loading Change

Page 4:-

- Logo change 
- Row changes

**Comment by Priyansh-15** [comment]
UI Update : 

- Logo Change for Each Company ( Page 4 UI ).
- Apply Now Remove and add URL to Job Name ( Page 4) .
- each job desc width fixed ( issue in exceeding data ) ( Page 4 ).
- Title Icon and name ( All Pages )
