### ISSUE TITLE
unit test -Google

### ISSUE THREAD

**Issue by Priyansh-15** [Priyansh-15/Job_Helper#17]

**Comment by Shubham-Godambe** [comment]
Hey can you plz describe the issue?

**Comment by Priyansh-15** [comment]
> Hey can you plz describe the issue? 

Hi @Shubham-Godambe 
The aim is to write some good `unit test` for testing purpose for the `google module` in `job helper` and to solve any bugs left (if any) in the existing unit tests for the same.

Feel free to communicate and share your ideas regarding the project  in the discussion section.
@Priyansh-15  :)
